### PR TITLE
Cleanups for senseme devices

### PR DESCRIPTION
**Pull request by bdraco**
- Reduce code duplication
- Call async function in async context
- Add suggested area support
- Ensure dispatcher is removed when entity is removed
- Remove side effects from init

### CODE REVIEW

**Comment by bdraco** [comment]
Still need to validate the change to async is ok as I haven't traced all the I/O

**Comment by bdraco** [comment]
Verified I/O is happening async so switching to `async` methods works as expected

**Comment by mikelawrence** [comment]
I definitely like your suggestions will work these changes in, however... I have been working on some substantial changes on both the underlying library (aiosenseme) and this component. I have the new fan model (2021.3) working and was waiting to release that update after Home Assistant 2021.3 is released. The new code is in the loadip branch of this component. I have already released a new version of the [aiosensme library](https://github.com/mikelawrence/aiosenseme). 

Give me some time to look at these changes more in-depth tonight (North American Central Standard Time).

**Comment by mikelawrence** [comment]
Looks good thanks! Will merge these changes into next release.

**Comment by bdraco** [comment]
Thanks. The developer docs (https://developers.home-assistant.io/docs/core/entity/fan) where behind being updated a bit so I wanted to make I mention that we added `speed_count` to the `fan` model last week https://github.com/home-assistant/core/pull/46512

**Comment by mikelawrence** [comment]
Thanks for the heads up. I didn't look at any of this last week my internet access went out early last week and I didn't get it back until Sunday.

**Comment by bdraco** [comment]
> Thanks for the heads up. I didn't look at any of this last week my internet access went out early last week and I didn't get it back until Sunday.

At least the boil notice is lifted now!

**Comment by mikelawrence** [comment]
Well we are still under a boil notice...Water went out again yesterday. I think they were repairing lines which basically caused a reset of the boil notice.

**Comment by bdraco** [comment]
> Well we are still under a boil notice...Water went out again yesterday. I think they were repairing lines which basically caused a reset of the boil notice.

What a mess. We are fixing pipes in Houston and trying to source parts with little success. Hope it gets better for you soon.

**Comment by mikelawrence** [comment]
My brother had a hero of a plumber with supplies from Missouri fix his broken pipes in Sugarland today. It's been hard on a lot of people. I think my family has had some good luck this time while others not some much!

**Comment by bdraco** [comment]
> My brother had a hero of a plumber with supplies from Missouri fix his broken pipes in Sugarland today. It's been hard on a lot of people. I think my family has had some good luck this time while others not some much! 

Other have definitely had a much worse time. My brother is in Austin and it seems like they didn't fare as well as Houston as they are still filtering water themselves. Usually we do worse with the hurricanes. The whole situation is just a bit sad.

**Pull request merged**
